import * as _1e from '@minecraft/server-editor-bindings';

// Enums - 6
export enum EditorRealmsServiceAvailability { DedicatedServer = 2, NoRealmsSubscription = 1, NotLoggedIn = 0, NotServerHost = 3, Success = 4, Unknown = 5};
export enum PersistenceGroupType { Local = 0, Shared = 2};
export enum PersistenceScope { ClientGlobal = 1, ClientProject = 0, ServerGlobal = 3, ServerProject = 2};
export enum ProjectRegionAvailabilityMode { Loaded = 0, Ticking = 1};
export enum RealmsServiceStatus { Exporting = 2, Fetching = 0, Idle = 1, Uploading = 3};
export enum RealmsWorldUploadResult { EditorSystemFailure = 4, ExportWorldFailure = 2, Success = 1, Unknown = 0, UploadWorldFailure = 3, WorldNameNonCompliant = 6, WorldUploadBusy = 5};

// Interfaces - 7
export interface DataTransferCollectionNameData { nameStringId: string; uniqueId: string};
export interface EditorRealmsWorld { id: string; name: string};
export interface EditorRealmsWorldSlot { id: number; name: string};
export interface InputBindingInfo { actionId?: string; canRebind: boolean; label?: string; tooltip?: string};
export interface PersistenceGroupCreationOptions { groupType?: PersistenceGroupType; scope: PersistenceScope; version?: number};
export interface PersistenceQueryGroupOptions { namespace?: string; namespacedName?: string; scope?: PersistenceScope; version?: number};
export interface ProjectRegionOptions { availabilityMode?: ProjectRegionAvailabilityMode; extentX: _2c.NumberRange; extentZ: _2c.NumberRange};

// Classes - 22
export class DataStore { public readonly actionBarContainer: DataStoreActionBarContainer; public readonly actionContainer: DataStoreActionContainer; public readonly afterEvents: DataStoreAfterEvents; public readonly menuContainer: DataStoreMenuContainer; public readonly modalToolContainer: DataStoreModalToolContainer; public readonly paneContainer: DataStorePaneContainer; private constructor();};
export class DataStoreActionBarContainer { public getItemPayload(id: string): string; public getItemProperty(id: string, property: string): (boolean | number | string | undefined); public hasItemPayload(id: string): boolean; public hasItemProperty(id: string, property: string): boolean; public registerItem(id: string, payload: string): void; public unregisterItem(id: string): void; public updateRegisteredItem(id: string, payload: string): void; public updateRegisteredItemProperty(id: string, payload: string, property: string): void; private constructor();};
export class DataStoreActionContainer { public bindActionToControl(controlId: string, actionPayload: string): void; public removeActionFromControl(controlId: string, actionPayload?: string): void; private constructor();};
export class DataStoreAfterEvents { public readonly payloadReceived: DataStorePayloadAfterEventSignal; private constructor();};
export class DataStoreMenuContainer { public createItem(id: string, payload: string): void; public destroyItem(id: string): void; public getPayload(id: string): string; public getProperty(id: string, property: string): (boolean | number | string | undefined); public hasPayload(id: string): boolean; public hasProperty(id: string, property: string): boolean; public updateItem(id: string, payload: string): void; private constructor();};
export class DataStoreModalToolActivationChangedEvent { public readonly isActive: boolean; public readonly toolId?: string; private constructor();};
export class DataStoreModalToolActivationChangedEventSignal { public subscribe(callback: (arg0: DataStoreModalToolActivationChangedEvent)=>void): (arg0: DataStoreModalToolActivationChangedEvent)=>void; public unsubscribe(callback: (arg0: DataStoreModalToolActivationChangedEvent)=>void): void; private constructor();};
export class DataStoreModalToolContainer { public readonly toolActivationChanged: DataStoreModalToolActivationChangedEventSignal; public getSelectedTool(): (string | undefined); public getToolPayload(id: string): string; public getToolProperty(id: string, property: string): (boolean | number | string | undefined); public hasToolPayload(id: string): boolean; public hasToolProperty(id: string, property: string): boolean; public registerTool(id: string, payload: string): void; public unregisterTool(id: string): void; public updateRegisteredTool(id: string, payload: string): void; public updateRegisteredToolProperty(id: string, payload: string, property: string): void; public updateSelectedTool(toolId?: string): void; private constructor();};
export class DataStorePaneContainer { public createPane(id: string): void; public destroyPane(id: string): void; private constructor();};
export class DataStorePayloadAfterEvent { public readonly dataTag: string; public readonly payload: string; private constructor();};
export class DataStorePayloadAfterEventSignal { public subscribe(callback: (arg0: DataStorePayloadAfterEvent)=>void): (arg0: DataStorePayloadAfterEvent)=>void; public unsubscribe(callback: (arg0: DataStorePayloadAfterEvent)=>void): void; private constructor();};
export class DataTransferManager { public closeSession(collectionUniqueId: string): void; public getRegisteredAccessors(): DataTransferCollectionNameData[]; public openSession(collectionUniqueId: string): void; public requestData(collectionUniqueId: string, useSnapshot?: boolean): Promise<DataTransferRequestResponse>; public sendData(collectionUniqueId: string, jsonData: string): void; public sendDataToClipboard(jsonData: string): void; private constructor();};
export class DataTransferRequestResponse { public readonly collectionName: string; public readonly data: string; public readonly schema: string; private constructor();};
export class InputService { public focusViewport(): void; public getKeyBindingProcessingState(contextId: string, bindingId: string): (number | undefined); public registerKeyBinding(contextId: string, bindingId: string, key: number, modifier: _1e.InputModifier, info: InputBindingInfo): void; public registerMouseBinding(contextId: string, bindingId: string, mouseAction: _1e.MouseActionCategory): void; public unregisterKeyBinding(contextId: string, bindingId: string): void; public unregisterMouseBinding(contextId: string, bindingId: string): void; public updateKeyBindingProcessingState(contextId: string, bindingId: string, state?: number): void; private constructor();};
export class InternalPersistenceManager { public createGroup(namespacedName: string, options: PersistenceGroupCreationOptions): PersistenceGroup; public deleteGroup(namespacedName: string, options: PersistenceGroupCreationOptions): void; public disposeAllGroups(): void; public fetchGroups(options: PersistenceQueryGroupOptions): PersistenceGroup[]; public getGroup(namespacedName: string, options: PersistenceGroupCreationOptions): (PersistenceGroup | undefined); public getOrCreateGroup(namespacedName: string, options: PersistenceGroupCreationOptions): PersistenceGroup; private constructor();};
export class InternalPlayerServiceContext { public readonly dataStore: DataStore; public readonly dataTransfer: DataTransferManager; public readonly input: InputService; public readonly internalPersistenceManager: InternalPersistenceManager; public readonly realmsService: RealmsService; public readonly regionManager: ProjectRegionManager; private constructor();};
export class MinecraftEditorInternal { public readonly isNewLevel: boolean; public fireTelemetryEvent(player: _3e.Player, source: string, eventName: string, metadata: string): void; public getPlayerServices(player: _3e.Player): InternalPlayerServiceContext; public registerExtension(extensionName: string, activationFunction: (arg0: _1e.ExtensionContext)=>void, shutdownFunction: (arg0: _1e.ExtensionContext)=>void, options?: _1e.ExtensionOptionalParameters): _1e.Extension; private constructor();};
export class PersistenceGroup { public createItem(itemName: string, defaultJsonValue?: string): PersistenceGroupItem; public deleteItem(itemName: string): void; public dispose(): boolean; public disposeAllGroupItems(): void; public disposeGroupItem(key: string): boolean; public fetchItem(itemName: string): PersistenceGroupItem; public getOrCreateItem(itemName: string, defaultJsonValue?: string): PersistenceGroupItem; public listItems(): string[]; private constructor();};
export class PersistenceGroupItem { public commit(): void; public getAsJSON(): string; public getKey(): string; public getValue(): string; public setValue(value: string): void; private constructor();};
export class ProjectRegion { public readonly availabilityMode: ProjectRegionAvailabilityMode; public readonly id: string; public readonly isValid: boolean; public dispose(): boolean; public getAvailableLocationFromRay(location: _3e.Vector3, direction: _3e.Vector3, options?: _3e.BlockRaycastOptions): (_3e.Vector3 | undefined); public getBlock(location: _3e.Vector3): (_3e.Block | undefined); public getBlockMapColor(location: _3e.Vector3): _3e.RGBA; public getBlockPermutation(location: _3e.Vector3): _3e.BlockPermutation; public getBlockTypeId(location: _3e.Vector3): string; public getBounds(): _3e.BlockBoundingBox; public isAirBlock(location: _3e.Vector3): boolean; public isAreaAvailable(boundingBox: _3e.BlockBoundingBox): boolean; public isAvailable(): boolean; public isBlockWaterLogged(location: _3e.Vector3): boolean; public isLiquidBlock(location: _3e.Vector3): boolean; public isLocationAvailable(location: _3e.Vector3): boolean; public isSolidBlock(location: _3e.Vector3): boolean; public requestBlockOperationArea(volume: _1e.RelativeVolumeListBlockVolume, callback: (arg0: _3e.BlockLocationIterator)=>void): Promise<void>; public requestExpandToContain(extentX: _2c.NumberRange, extentZ: _2c.NumberRange): Promise<void>; public requestExtentsUpdate(extentX: _2c.NumberRange, extentZ: _2c.NumberRange): Promise<void>; public requestMove(center: _3e.Vector3): Promise<void>; public setBlockType(location: _3e.Vector3, blockType: _3e.BlockType | string): void; public setBlockWaterlogged(location: _3e.Vector3, isWaterlogged: boolean): void; public spawnEntity(identifier: _3e.EntityType | string, location: _3e.Vector3, rotation?: number): _3e.Entity; public waitUntilAvailable(): Promise<void>; public waitUntilBoundsAvailable(boundingBox: _3e.BlockBoundingBox): Promise<void>; private constructor();};
export class ProjectRegionManager { public disposeAllRegions(): void; public disposeRegion(id: string): boolean; public getCursorRegion(): ProjectRegion; public getSelectionRegion(): ProjectRegion; public leaseRegion(options: ProjectRegionOptions): ProjectRegion; private constructor();};
export class RealmsService { public beginDownloadFromRealms(realmsWorldId: string, slotId: number): Promise<string>; public beginUploadToRealms(realmsWorldId: string, slotId: number, gameOptions: _1e.GameOptions): Promise<RealmsWorldUploadResult>; public canUploadWorld(): boolean; public getRealmWorldlist(): Promise<EditorRealmsWorld[]>; public getServiceStatus(): RealmsServiceStatus; public getSlots(worldId: string): Promise<EditorRealmsWorldSlot[]>; public isRealmsServiceAvailable(): EditorRealmsServiceAvailability; private constructor();};

// Constants & Objects - 1

export const editorInternal: MinecraftEditorInternal;

// Functions - 0

// Errors - 0
