name: Update Docs (Debug Mode)
on:
  workflow_dispatch:
    
permissions:
  contents: write
jobs:
  Debuger:
    runs-on: windows-latest
    env:
      OPTIONS_DEBUG: true
      ALWAYS_OVERWRITE: true
      DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        ref: "main"
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    - name: Install NPM
      run: |
        npm ci
    - name: Check Build Commit
      run: |
        npm run check-for-update