name: Update Docs (Debug Mode)
on:
  workflow_dispatch:
  push:
    branches: 
      main
    
permissions:
  contents: write
jobs:
  debugger:
    runs-on: windows-latest
    env:
      ALWAYS_OVERWRITE: true
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        ref: "main"

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.4
      with:
        node-version: '22'

    - name: Install pnpm
      run: corepack enable

    - name: Install dependencies with pnpm
      run: pnpm install --frozen-lockfile
  
    - name: Check TSC
      run: |
        pnpm run check

    - name: Build TS
      run: |
        pnpm run build-ts

    - name: Build
      run: |
        pnpm run build
      
    - name: Check Build Commit
      run: |
        pnpm run check-for-update