name: Update Docs (Debug Mode)
on:
    workflow_dispatch:
    push:
        branches: main
    pull_request:

jobs:
    debugger:
        runs-on: windows-latest
        env:
            ALWAYS_OVERWRITE: true
            DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: pnpm

            - name: Enable corepack
              run: corepack enable

            - name: Install dependencies with pnpm
              run: pnpm install

            - name: Run TSC without emit
              run: pnpm run check

            - name: Build
              run: pnpm run build

            - name: Check Build Commit
              run: pnpm run check-for-update
