name: Update Docs (Debug Mode)
on:
  workflow_dispatch:
  push:
    branches: 
      main
    
permissions:
  contents: write
jobs:
  Debuger:
    runs-on: windows-latest
    env:
      DEBUG_MODE: true
      ALWAYS_OVERWRITE: true
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        ref: "main"
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
    - name: Install NPM
      run: |
        npm i
    - name: Check TSC
      run: |
        npm run check
    - name: Build
      run: |
        npm run build
    - name: Check Build Commit
      run: |
        npm run check-for-update