name: Generate Docs
on:
   workflow_dispatch:

jobs:
  Generator:
    name: Generator
    runs_on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
