name: Check for New Docs
on: # schedule: - cron: '*/30 * * * *'
  push:
    branches:
        - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        ref: "development"
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # replace '14' with your desired Node.js version
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    - name: Configure Git
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "you@example.com"
        git config --global url."https://$GH_PAT@github.com/".insteadOf "https://github.com/"
    - name: Install NPM
      run: |
        npm ci
    - name: Check Build Commit
      run: |
        node .