name: CI Generate
on:
   push:
      branches: main
   workflow_dispatch:

permissions:
   contents: write
jobs:
   generator:
      runs-on: ubuntu-latest
      steps:
         - name: Check versions
           id: version
           run: |
              bash check-version.sh
              if [ $? -eq 0 ]; then
                 echo "should_continue=false" >> $GITHUB_OUTPUT
                 echo "No update required. Exiting early."
              else
                 echo "should_continue=true" >> $GITHUB_OUTPUT
                 echo "Update required. Continuing."
              fi

         - uses: denoland/setup-deno@v1
           if: steps.version.outputs.should_continue == 'true'
           with:
            deno-version: ">=2.4"

         - name: Run Deno
           run: deno run --allow-all "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/dist/main.js"
