name: Check for New Docs
on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
        - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        ref: "main"
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # replace '14' with your desired Node.js version
    - name: Install NPM
      run: |
        npm ci
    - name: Check Build Commit
      run: |
        node .