name: Update Docs Generator
on:
  push:
    branches: 
      main
  schedule: 
  - cron: '*/120 * * * *'
permissions:
  contents: write
jobs:
  Main-Updater:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        ref: "main"
        fetch-depth: '0'
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    - name: Install NPM
      run: |
        npm ci
    - name: Check Build Commit
      run: |
        npm run check-for-update
