name: Check for New Docs
on:
  push: 
  #schedule: 
  #- cron: '*/15 * * * *'
permissions:
  contents: write
jobs:

  build:
    runs-on: windows-latest
    env:
      OPTIONS_DEBUG: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        ref: "main"
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    - name: Install NPM
      run: |
        npm ci
    - name: Check Build Commit
      run: |
        node .      
    - name: Set color
      id: color-selector
      run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
    - name: Set Output
      id: ouput-selector
      run: echo "status=neutral" >> "$GITHUB_OUTPUT"
