name: Update Docs
on:
  push: 
  #schedule: 
  #- cron: '*/20 * * * *'
permissions:
  contents: write
jobs:

  build:
    runs-on: windows-latest
    env:
      OPTIONS_DEBUG: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        ref: "main"
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    - name: Install NPM
      run: |
        npm ci
    - name: Check Build Commit
      run: |
        node .