name: CI Generate
on:
   push:
      branches: main
   workflow_dispatch:

permissions:
   contents: write
jobs:
   generator:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
              ref: 'main'
              fetch-depth: '0'

         - name: Setup Latest NodeJS
           uses: actions/setup-node@v4
           with:
              node-version: 'latest'
              run_install: false

         - name: Setup pnpm
           uses: pnpm/action-setup@v2
           with:
               version: latest

         - name: Install dependencies with pnpm
           run: pnpm install

         - name: Check TSC
           run: |
              pnpm run check

         - name: Build
           run: |
              npm run build

         - name: Check Build Commit
           run: |
              npm run check-for-update
